- backend/.eslintrc.json
- backend/.gitignore
- backend/index.js
- backend/package-lock.json
- backend/package.json
Fixes #2
- setting up the backend
- setting up ESLinter
index.md`).
> Setting up  backend

- .github/workflows/run_eslint_backend.yml
Fixes #6 
- added automated eslint checker as github action
index.md`).
> Github workflow for automating the linting process

- backend/config/swagger.js
- backend/docs/paths/index.js
- backend/docs/schemas/index.js
- backend/index.js
- backend/package-lock.json
- backend/package.json
Fixes #8 
- setup swagger
- add boiler plate for documentation 
index.md`).
> Setup swagger

- README.md
Fixes #11 
added status check
index.md`).
> Add status checks and Update `readme`

- frontend/src/actions/userActions.js
> Login backend

- frontend/src/auth/PrivateRoute.js
- frontend/src/auth/index.js
Fixes #34 
- add authentication function 
- add PrivateRoute component 
index.md`).
> Private routing

- frontend/src/Home.js
Fixes #[issue number]
index.md`).
> fixed homepage css

- backend/models/categories.js
- backend/models/order_products.js
- backend/models/orders.js
- backend/models/products.js
- backend/models/tables.js
- backend/models/users.js
Fixes #50 
- Modified `pre-save` hook in `users` schema
- Add schema for the following collections:
-  `categories`
- `products`
- `tables`
- `ordes`
- `order_products`
- Add supplementary function related to order schema which is required for many many relation between `orders` and `products`
index.md`).
> Add model schema

- backend/middlewares/validation.js
- backend/package-lock.json
- backend/package.json
- backend/routes/auth.js
- backend/validators/auth.js
Fixes #52 
- Added `joi` module
- Added validation schema for authentication
index.md`).
> Add validation login

- backend/.babelrc.json
- backend/.eslintrc.json
- backend/.gitignore
- backend/package-lock.json
- backend/package.json
- backend/tests/sample.test.js
Fixes #54 
- Added `jest` module along with `supertest`
- Added sample test
index.md`).
> Setup jest

- .github/workflows/run_jest_testing_backend.yml
Fixes #58 
Added action
index.md`).
> Add workflow

- backend/app.js
- backend/controllers/category.js
- backend/package-lock.json
- backend/package.json
- backend/routes/category.js
- backend/validators/category.js
Fixes #60 
- Added validation for categories
- Added controllers for categories
- Added routes for categories
index.md`).
> Add cat route

- backend/docs/paths/category.js
- backend/docs/paths/index.js
- backend/docs/schemas/category.js
- backend/docs/schemas/index.js
Fixes #63 
- added schema for categories 
- added paths for categories
index.md`).
> Add doc cat

- backend/app.js
- backend/controllers/table.js
- backend/routes/table.js
- backend/validators/table.js
- frontend/package-lock.json
Fixes #62 
**Technical details**'
- added validators for tables
- added controller for tables
- added routes for tables 
- updated app.js in backend for tables
index.md`).
> Issue <Crud tables> resolved.

- backend/app.js
- backend/controllers/product.js
- backend/routes/product.js
- backend/validators/product.js
> Crud product

- backend/app.js
- backend/controllers/order.js
- backend/docs/paths/index.js
- backend/docs/paths/order.js
- backend/docs/schemas/index.js
- backend/docs/schemas/order.js
- backend/middlewares/order.js
- backend/routes/order.js
- backend/routes/table.js
- backend/utils/order.js
- backend/validators/order.js
Fixes #83 
- Add validators for `orders`
- Add helper functions for `orders`
- Add controllers for `orders`
- Add middlewares for `orders`
- Add routes for `orders`
- Add swagger documentation for `orders`
index.md`).
> Add order route

- backend/app.js
- backend/controllers/users.js
- backend/docs/paths/index.js
- backend/docs/paths/users.js
- backend/docs/schemas/index.js
- backend/docs/schemas/users.js
- backend/routes/users.js
Fixes #84 
- Add controllers for `users`
- Add routes for `users`
- Add swagger documentation for `users`
index.md`).
> Add users route

- frontend/src/Main.js
- frontend/src/components/form/Checkbox.js
- frontend/src/components/form/Textarea.js
- frontend/src/components/loader/SvgLoaders.js
- frontend/src/components/order/OrderCart.js
- frontend/src/components/order/OrderInfo.js
- frontend/src/components/order/ProductsTable.js
- frontend/src/screens/order/OrderCreateScreen.js
Fixes #88 
New order functionality added 
index.md`).
> Order create screen

- frontend/src/Main.js
- frontend/src/components/ViewBox.js
- frontend/src/screens/order/OrderViewScreen .js
Fixes #89 
Frontend added for viewing the order screen
index.md`).
> Order view

- backend/validators/product.js
- frontend/src/components/form/Input.js
- frontend/src/screens/product/ProductScreen.js
Fixes #[issue number]
- fixed min value bug in frontend and backend
index.md`).
> Fix min bug

- frontend/src/Main.js
- frontend/src/screens/order/OrderEditScreen.js
- frontend/src/screens/order/OrderViewScreen .js
Fixes #90 
Added UI for order edit functionality
index.md`).
> Order edit

- frontend/src/Main.js
- frontend/src/components/Table.js
- frontend/src/components/loader/SkeletonLoaders.js
- frontend/src/screens/order/ActiveOrdersScreen.js
- frontend/src/screens/product/ProductEditScreen.js
- frontend/src/screens/product/ProductScreen.js
Fixes #91 
Active orders screen UI added
index.md`).
> active order

- backend/tests/unit/categorySchema.test.js
- backend/tests/unit/orderSchema.test.js
- backend/tests/unit/productSchema.test.js
- backend/tests/unit/tableSchema.test.js
- backend/validators/category.js
- backend/validators/order.js
- backend/validators/product.js
- backend/validators/table.js
Fixes #105 
- Add unit tests for `categorySchema`
- Add unit tests for `tableSchema`
- Add unit tests for `productSchema`
- Add unit tests for `orderSchema`
index.md`).
> Add unit tests
